In [25]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

# 파일 불러오기

In [26]:
df = pd.read_csv("C:\\AI\\seeds_dataset.txt", delim_whitespace = True, header = None) # 컬럼이 없을때는 header = None 붙이기

# 컬럼을 붙이고 싶다면 
df.columns = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'label']
df

C:\Users\송민수\AppData\Local\Temp\ipykernel_9240\3722849383.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv("C:\\AI\\seeds_dataset.txt", delim_whitespace = True, header = None) # 컬럼이 없을때는 header = None 붙이기


A      B       C      D      E      F      G  label
0    15.26  14.84  0.8710  5.763  3.312  2.221  5.220      1
1    14.88  14.57  0.8811  5.554  3.333  1.018  4.956      1
2    14.29  14.09  0.9050  5.291  3.337  2.699  4.825      1
3    13.84  13.94  0.8955  5.324  3.379  2.259  4.805      1
4    16.14  14.99  0.9034  5.658  3.562  1.355  5.175      1
..     ...    ...     ...    ...    ...    ...    ...    ...
205  12.19  13.20  0.8783  5.137  2.981  3.631  4.870      3
206  11.23  12.88  0.8511  5.140  2.795  4.325  5.003      3
207  13.20  13.66  0.8883  5.236  3.232  8.315  5.056      3
208  11.84  13.21  0.8521  5.175  2.836  3.598  5.044      3
209  12.30  13.34  0.8684  5.243  2.974  5.637  5.063      3

[210 rows x 8 columns]

In [27]:
X=df.drop('label',axis=1)
X.head()

A      B       C      D      E      F      G
0  15.26  14.84  0.8710  5.763  3.312  2.221  5.220
1  14.88  14.57  0.8811  5.554  3.333  1.018  4.956
2  14.29  14.09  0.9050  5.291  3.337  2.699  4.825
3  13.84  13.94  0.8955  5.324  3.379  2.259  4.805
4  16.14  14.99  0.9034  5.658  3.562  1.355  5.175

In [28]:
y=df['label']
y.value_counts()

label
1    70
2    70
3    70
Name: count, dtype: int64

In [29]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: label, dtype: int64

In [30]:
y

0      1
1      1
2      1
3      1
4      1
      ..
205    3
206    3
207    3
208    3
209    3
Name: label, Length: 210, dtype: int64

In [31]:
Y = pd.get_dummies(y).values

In [32]:
Y

array([[ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ T

In [33]:
X = X.values

In [34]:
from sklearn.model_selection import train_test_split

# 먼저 8:2 비율로 트레인 : 임시 데이터 나누기
X_train, X_temp, y_train, y_temp = train_test_split(X, Y, test_size=0.2, random_state=0)

# 임시 데이터를 1:1 비율로 valid : 테스트 데이터 나누기 
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=0)

# shape를 통해 제대로 분리 됐는지 확인
print(X_train.shape, X_val.shape, X_test.shape, y_train.shape, y_val.shape, y_test.shape)

(168, 7) (21, 7) (21, 7) (168, 3) (21, 3) (21, 3)


In [35]:
# 1번째 방법. model1

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam

model1 = Sequential()

model1.add(Dense(64,input_shape=(7,),activation='relu'))
model1.add(Dense(32,activation='relu'))
model1.add(Dense(16,activation='relu'))
model1.add(Dense(10,activation='relu'))
model1.add(Dense(3,activation='softmax'))

model1.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

model1.summary()

C:\Users\송민수\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                     │ (None, 64)                  │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_21 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_22 (Dense)                     │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_23 (Dense)                     │ (None, 10)                  │             170 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_24 (Dense)                     │ (None, 3)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,323 (12.98 KB)

 Trainable params: 3,323 (12.98 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
model_history = model1.fit(x=X_train, y=y_train, epochs=30, batch_size=32, validation_data=(X_val,y_val))
y_pred = model1.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.3434 - loss: 1.3908 - val_accuracy: 0.2381 - val_loss: 1.1584
Epoch 2/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3590 - loss: 1.1055 - val_accuracy: 0.2381 - val_loss: 1.0979
Epoch 3/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3862 - loss: 1.0746 - val_accuracy: 0.4762 - val_loss: 1.0651
Epoch 4/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5240 - loss: 1.0615 - val_accuracy: 0.5238 - val_loss: 1.0271
Epoch 5/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4748 - loss: 1.0155 - val_accuracy: 0.2857 - val_loss: 0.9985
Epoch 6/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4488 - loss: 0.9840 - val_accuracy: 0.2381 - val_loss: 1.0014
Epoch 7/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4206 - loss: 0.9681 - val_accuracy: 0.3333 - val_loss: 0.9863
Epoch 8/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5840 - loss: 0.9239 - val_accuracy: 0.4286 - val_loss: 0.9684
E

In [37]:
# model 1 결과
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         6
           1       0.78      1.00      0.88         7
           2       0.89      1.00      0.94         8

    accuracy                           0.86        21
   macro avg       0.89      0.83      0.83        21
weighted avg       0.88      0.86      0.84        21

[[3 2 1]
 [0 7 0]
 [0 0 8]]


In [38]:
# 2번째 방법. model2
from keras.models import Model
from keras.layers import Input, Dense
from keras.optimizers import Adam

inputs = Input(shape=(7,))
x = Dense(64, activation='relu')(inputs)
x = Dense(32, activation='relu')(x)
x = Dense(16, activation='relu')(x)
x = Dense(10, activation='relu')(x)
prediction = Dense(3, activation='softmax')(x)

model2 = Model(inputs=inputs, outputs=prediction)

model2.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

model2.summary()

Model: "functional_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_4 (InputLayer)           │ (None, 7)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_25 (Dense)                     │ (None, 64)                  │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_26 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_27 (Dense)                     │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_28 (Dense)                     │ (None, 10)                  │             170 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_29 (Dense)                     │ (None, 3)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,323 (12.98 KB)

 Trainable params: 3,323 (12.98 KB)

 Non-trainable params: 0 (0.00 B)

In [39]:
model_history = model2.fit(x=X_train, y=y_train, epochs=30, batch_size=32, validation_data=(X_val,y_val))
y_pred = model2.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.3356 - loss: 1.1998 - val_accuracy: 0.2857 - val_loss: 1.0857
Epoch 2/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4372 - loss: 1.0626 - val_accuracy: 0.4286 - val_loss: 1.0374
Epoch 3/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3888 - loss: 1.0390 - val_accuracy: 0.7619 - val_loss: 1.0219
Epoch 4/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7274 - loss: 1.0112 - val_accuracy: 0.6667 - val_loss: 0.9937
Epoch 5/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6758 - loss: 0.9780 - val_accuracy: 0.6667 - val_loss: 0.9818
Epoch 6/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6385 - loss: 0.9556 - val_accuracy: 0.4762 - val_loss: 0.9891
Epoch 7/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6551 - loss: 0.9171 - val_accuracy: 0.5714 - val_loss: 0.9596
Epoch 8/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7462 - loss: 0.9066 - val_accuracy: 0.7143 - val_loss: 0.9097


In [40]:
# model 2 결과
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.71      0.83      0.77         6
           1       1.00      0.71      0.83         7
           2       0.89      1.00      0.94         8

    accuracy                           0.86        21
   macro avg       0.87      0.85      0.85        21
weighted avg       0.88      0.86      0.86        21

[[5 0 1]
 [2 5 0]
 [0 0 8]]


In [41]:
# 3번째 방법. model3
import tensorflow as tf
from keras.models import Model
from keras.layers import Dense

class SimpleMLP(Model):
    def __init__(self):
        super(SimpleMLP, self).__init__()
        self.dense1 = Dense(64, activation='relu')
        self.dense2 = Dense(32, activation='relu')
        self.dense3 = Dense(16, activation='relu')
        self.dense4 = Dense(10, activation='relu')
        self.dense5 = Dense(3, activation='softmax')

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        x = self.dense3(x)
        x = self.dense4(x)
        return self.dense5(x)

model3 = SimpleMLP()

model3.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

model3.summary() 

Model: "simple_mlp_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_30 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_31 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_32 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_33 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_34 (Dense)                     │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [42]:
model_history = model3.fit(x=X_train, y=y_train, epochs=30, batch_size=32, validation_data=(X_val,y_val))
y_pred = model3.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.4049 - loss: 1.6529 - val_accuracy: 0.4286 - val_loss: 1.0831
Epoch 2/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3307 - loss: 1.1864 - val_accuracy: 0.4286 - val_loss: 1.0606
Epoch 3/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3461 - loss: 1.1550 - val_accuracy: 0.5714 - val_loss: 1.0643
Epoch 4/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3963 - loss: 1.1017 - val_accuracy: 0.3333 - val_loss: 1.0864
Epoch 5/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3352 - loss: 1.1068 - val_accuracy: 0.3333 - val_loss: 1.0773
Epoch 6/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3654 - loss: 1.0894 - val_accuracy: 0.3333 - val_loss: 1.0591
Epoch 7/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3798 - loss: 1.0814 - val_accuracy: 0.5714 - val_loss: 1.0452
Epoch 8/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5769 - loss: 1.0673 - val_accuracy: 0.6667 - val_loss: 1.0353
E

In [43]:
# model 3 결과
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.50      0.33      0.40         6
           1       0.62      0.71      0.67         7
           2       0.89      1.00      0.94         8

    accuracy                           0.71        21
   macro avg       0.67      0.68      0.67        21
weighted avg       0.69      0.71      0.70        21

[[2 3 1]
 [2 5 0]
 [0 0 8]]
