In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

# 파일 불러오기

In [18]:
df = pd.read_csv("C:\\AI\\wine.csv") # 컬럼이 없을때는 header = None 붙이기
df
# 컬럼을 붙이고 싶다면 
# df.columns = ['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety','output']

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0       1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1       1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2       1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3       1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4       1    13.24        2.59  2.87  21.0  118     2.80        2.69   
..    ...      ...         ...   ...   ...  ...      ...         ...   
173     3    13.71        5.65  2.45  20.5   95     1.68        0.61   
174     3    13.40        3.91  2.48  23.0  102     1.80        0.75   
175     3    13.27        4.28  2.26  20.0  120     1.59        0.69   
176     3    13.17        2.59  2.37  20.0  120     1.65        0.68   
177     3    14.13        4.10  2.74  24.5   96     2.05        0.76   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                    0.28     2.29       5.64  1.04  3.92     1065  
1                    0.26     1.28       4.38  1.05  3.40     1050  
2                    0.30     2.81       5.68  1.03  3.17     1185  
3                    0.24     2.18       7.80  0.86  3.45     1480  
4                    0.39     1.82       4.32  1.04  2.93      735  
..                    ...      ...        ...   ...   ...      ...  
173                  0.52     1.06       7.70  0.64  1.74      740  
174                  0.43     1.41       7.30  0.70  1.56      750  
175                  0.43     1.35      10.20  0.59  1.56      835  
176                  0.53     1.46       9.30  0.60  1.62      840  
177                  0.56     1.35       9.20  0.61  1.60      560  

[178 rows x 14 columns]

In [19]:
# 불필요한 컬럼 제거 
#df.drop(columns=['id'], inplace=True)

# 문자형 데이터를 숫자로 변환 (엔코딩)
#encoder = LabelEncoder()
#df['price'] = encoder.fit_transform(df['price'])
#df['maint'] = encoder.fit_transform(df['maint'])
#df['doors'] = encoder.fit_transform(df['doors'])
#df['persons'] = encoder.fit_transform(df['persons'])
#df['lug_capacity'] = encoder.fit_transform(df['lug_capacity'])
#df['safety'] = encoder.fit_transform(df['safety'])


# 결측치 확인

In [20]:
df.isnull().sum()

Wine                    0
Alcohol                 0
Malic.acid              0
Ash                     0
Acl                     0
Mg                      0
Phenols                 0
Flavanoids              0
Nonflavanoid.phenols    0
Proanth                 0
Color.int               0
Hue                     0
OD                      0
Proline                 0
dtype: int64

In [21]:
# 결측치를 평균값으로 채우기 (있을때만)
# df.fillna(df.mean(), inplace=True) 

# 특성과 라벨 분리 
X = df.drop(columns=['Wine'])
y = df['Wine']

# 정규화 및 데이터 분할

In [22]:
# 정규화 
scaler = StandardScaler()
X = scaler.fit_transform(X)

# 훈련/테스트 데이터 분할 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# shape를 통해 제대로 분리 됐는지 확인
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(142, 13) (36, 13) (142,) (36,)


# SVM

In [23]:
# SVM
clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
1.0
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]


# DecisionTree / DT

In [24]:
# DecisionTree / DT
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.9722222222222222
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]


# RandomForest / RF

In [25]:
# RandomForest / RF
rf = RandomForestClassifier(random_state=0)
rf.fit(X_train, y_train)

pred_rf = rf.predict(X_test)

print ("\n--- Random Forest ---")
print (accuracy_score(y_test,pred_rf))
print (confusion_matrix(y_test, pred_rf))


--- Random Forest ---
0.9722222222222222
[[14  0  0]
 [ 0 15  1]
 [ 0  0  6]]


# KNN

In [26]:
# KNN
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

pred_knn = knn.predict(X_test)

print ("\n--- KNN ---")
print (accuracy_score(y_test,pred_knn))
print (confusion_matrix(y_test, pred_knn))


--- KNN ---
0.9444444444444444
[[14  0  0]
 [ 1 14  1]
 [ 0  0  6]]


# LogisticRegression

In [27]:
# LogisticRegression / LR
lr = LogisticRegression(random_state=0)
lr.fit(X_train, y_train)

pred_lr = lr.predict(X_test)

print ("\n--- LR ---")
print (accuracy_score(y_test,pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- LR ---
1.0
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
